[package]
name = "passgen"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug-assertions = false
overflow-checks = false
panic = "abort"
strip = "debuginfo"

[dependencies]
arrayvec = "0.7.4"
clap = { version = "4.3.19", features = ["derive"] }
