[package]
name = "passgen"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
overflow-checks = false
panic = "abort"
strip = "symbols"

[dependencies]
clap = { version = "4", default-features = false, features = [
  "derive",
  "help",
  "std",
] }
