[package]
name = "passgen"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
overflow-checks = false
panic = "abort"
strip = "symbols"

[dependencies]
arrayvec = "0"
clap = { version = "4", features = ["derive"] }
